name: DMPWorldGuard
main: email.com.gmail.cosmoconsole.bukkit.deathmsg.wginterop.Main
version: 1.3
api-version: 1.13
description: Acts as a bridge between DeathMessagesPrime and WorldGuard.
author: CosmoConsole
depend: [DeathMessagesPrime, WorldGuard]